### ISSUE TITLE
What is the URL in errors?

### ISSUE THREAD

**Issue by ekr** [abetterinternet/prio-documents#108]
PPMAlert is:

~~~
struct {
  PPMTaskID task_id;
  opaque payload<1..255>;
} PPMAlert;
~~~

And the text says:

> where `task` is the associated PPM task (this value is always known) and
`payload` is the message. When sent by an aggregator in response to an HTTP
request, the response status is 400. When sent in a request to an aggregator,
the URL is always `[aggregator]/error`, where `[aggregator]` is the URL of the
aggregator endpoint.

Where does the URL appear?

**Comment by cjpatton** [comment]
The URL comes from the PPM parameters of the task.

**Comment by ekr** [comment]
I mean where does it go. There is no slot in this structure for "URL"

**Comment by ekr** [comment]
Fixed.
