### ISSUE TITLE
Message encoding

### ISSUE THREAD

**Issue by chris-wood** [abetterinternet/prio-documents#30]
We should specify structure and syntax for messages exchange in the protocol, e.g., data/proof shares. We'll pass these around with high-level HTTP APIs, maybe carried in JSON messages or whatever.

**Comment by cjpatton** [comment]
+1 to JSON blobs, as long as input shares can be encoded in binary. Seems to be the simplest to implement in JS.

**Comment by cjpatton** [comment]
I guess I don't much care if we need to encode input shares in base64 or whatever.

**Comment by cjpatton** [comment]
With #43 we are now using a binary format, specifically TLS syntax. Does anyone have any objections to continuing to use it?

**Comment by chris-wood** [comment]
None -- let's just stick with TLS. :-)
