### ISSUE TITLE
Which LICENSE is right?

### ISSUE THREAD

**Issue by martinthomson** [abetterinternet/prio-documents#39]
LICENSE (CC) or LICENSE.md ?

**Comment by cjpatton** [comment]
https://github.com/abetterinternet/prio-documents/blob/main/LICENSE

**Comment by cjpatton** [comment]
Thanks for flagging! I just pushed a fix.

**Comment by ekr** [comment]
I think we may actually want something more like CC(0). If we submit to IETF we don't want to carry this copyright notice around.
