### ISSUE TITLE
Rotation of HPKE keys for encrypting helper shares

### ISSUE THREAD

**Issue by tgeoghegan** [abetterinternet/prio-documents#49]
#43 includes a detailed specification of how helpers advertise HPKE configs for clients to use when encrypting helper shares. We should consider how key rotation works.

**Comment by cjpatton** [comment]
Might this just be deployment specific?

What we do for [the ECH extension for TLS](https://datatracker.ietf.org/doc/html/draft-ietf-tls-esni-10) is rotate the HPKE config every hour. To add reliability in case a client has an old key, we keep around a rotating set of keys from the last hour or so. The config id is used to determine which key was used to encrypt the payload.

**Comment by ekr** [comment]
This seems deployment specific.

**Comment by chris-wood** [comment]
I agree that the rotation _mechanism_ is deployment specific, but how the protocol reacts when a key rotation event occurs, possibly causing a mismatch between client and helper keys, should be in scope. (I assumed this issue was meant to address the latter.)

**Comment by chris-wood** [comment]
Do they need to agree, or should the data just naturally become invalid once rotation occurs?

**Comment by ekr** [comment]
It would be nice if submissions were rejected if they used invalid keys

**Comment by tgeoghegan** [comment]
Clients reports encrypted with a public key that's too old will indeed be rejected by helper. The validity period we're talking about is of interest for the collector in a protocol like Hits where the collector makes multiple, interactive requests to the aggregators: collectors need to have a sense of how long after the verify phase they can expect to be able to make collect requests before helpers are unable to decrypt the reports. i.e., collectors may not be able to make collect queries over reports that are more than 30 days old. In some cases, a validity period of hours could suffice if the successive queries are being made by an automated system, but maybe the queries are being formulated by a team of human analysts who need a day or so to consider what the n+1th query they want to send is based on the results of the nth query.

**Comment by cjpatton** [comment]
I think we might be converging on something like this: There's no explicit notion of report lifetime that's enforced by the protocol. Perhaps what we need instead is a way for the helper to tell the leader which reports are invalid and should be pruned. (Note that this is not unrelated to #57.)

**Comment by cjpatton** [comment]
Any solution to #57 will also solve this problem. I'm going to make a call and say this issue is a duplicate and can be closed.
