### ISSUE TITLE
Specify how clients choose helpers

### ISSUE THREAD

**Issue by tgeoghegan** [abetterinternet/prio-documents#50]
Currently, clients obtain a list of supported helpers from the leader. They are then expected to select some subset of the supported helpers to run the protocol with. Clients must be able to establish trust with helpers independently from the leader to prevent leaders from impersonating helpers and obtaining all the shares of an input.

While clients will establish an authenticated channel with helpers (typically over TLS), clients still need some way to know what helpers they trust (in the TLS case, what SANs they trust to run a helper).

The simplest way forward would be to require clients to maintain their own list of trusted helpers and intersect that with the list of supported helpers provided by the leader.

**Comment by cjpatton** [comment]
An even simpler solution (though it may not be desirable from a security standpoint) is to lean on X.509 and trust the client's set of root certificates. That is, if the client can verify the helper's SAN using one of its root certs, then it trusts whatever public key it gets from the helper over the secure channel.

**Comment by tgeoghegan** [comment]
This is now obsolete because we have agreed that PAParams will only have a single helper in them.
