### ISSUE TITLE
Consider using OHTTP 

### ISSUE THREAD

**Issue by tgeoghegan** [abetterinternet/prio-documents#58]
Prio v2 incorporates ingestion servers which sit between clients and aggregators. The ingestion servers:

- verify attestations from a trusted computing base in the client (i.e., secure enclave or TrustZone), making it harder for malicious clients to submit invalid inputs;
- remove any potentially identifying metadata from client reports before forwarding them to aggregators.

[Oblivious HTTP](https://datatracker.ietf.org/doc/draft-thomson-http-oblivious/) "allows a client to make multiple requests of a server without the server being able to link those requests to the client or to identify the requests as having come from the same client." We should see if we can integrate OHTTP into the DPA protocol as an optional extension that achieves the goals of the Prio v2 ingestion servers.

**Comment by cjpatton** [comment]
I think this issue is orthogonal to the PA protocol spec, but is certainly a useful enhancement for deployments.
