### ISSUE TITLE
Deployment architecture and PAParam

### ISSUE THREAD

**Issue by ekr** [abetterinternet/prio-documents#65]
In the current design, the leader provides the configuration information to the client in response to ```upload_start```.  This is conceptually problematic for several reasons:

1. The leader cannot be trusted to tell the client about the helpers because it might supply its own helpers.
2. The client learns all kinds of information it doesn't need (e.g., batch size).
3. It is an error for the client and the PA system to disagree about a number of parameters, so why are we giving this an opportunity for it to happen? For instance, suppose the client thinks it's doing Prio but the leader says it's doing heavy hitters? Why is that even possible.

Forgetting about the protocol for a second, IMO the right way for this to work is:

1. The *collector* decides on all the parameters, potentially in cooperation with the rest of the PA system (e.g., the leader might have a minimum batch size, not be able to do some protocol, etc.)
1. The *collector* then configures those parameters into the leader, helpers, etc. as well as the client
1. The *PA system* (probably the leader?) provides a task ID associated with those parameters.
1. The *client* connects to the leader and tells it it wants to use a specific task ID.
1. The leader then responds with an OK or error and any information that might be needed to actually deliver that data, which might well be empty (or could be "here is the node to upload to").

The key point here is that the client's trust relationship is with the collector, not the PA system, and so the PA system shouldn't be telling it much of anything.

Two asides:
1. You might, I suppose, want the collector to be able to reconfigure the client through the leader, but then this structure would need to be signed by the collector, which sounds like more trouble than it's worth.
1. You might also want some way to verify that there hadn't been some kind of configuration mismatch (e.g., the collector changed the size of the prime but didn't change the task ID) but the way you do that is by having the client supply a hash of the config and the leader return an error on mismatch.

**Comment by ekr** [comment]
To expand on these points a bit, the parameters need to be determined by the entity operating the collector and the propagated to:

1. The aggregators
1. The collector
1. The client

Only the first of these necessarily requires any kind of cooperation within the scope of this protocol: the collector and clients are effectively operated by the same entity and can be configured in some out of band mechanism. This leaves us with the aggregators. If we want to define a complete system, we might need some way for them to be in-band configured, though you could also imagine a simpler system in which that was done by some unspecified mechanism, which you'll probably need anyway for account creation etc. For instance, you could just have a Web page. If you do that, we don't need PAParam at all. OTOH, if we don't do that, then we need to define a helper configuration protocol.

**Comment by cjpatton** [comment]
Thanks for the thoughtful feedback, @ekr! I largely agree with how you envision the protocol working. The specific issues with the current spec notwithstanding, I think a big chunk of this question ties into nailing down how parameters are distributed, which we haven't done. It seems to me like the collector is going to have to sign PAParam at some point, at least so that the helper can ensure the leader isn't giving it the wrong parameters; but we probably don't want to require that the client be able to verify that signature.

> The key point here is that the client's trust relationship is with the collector, not the PA system, and so the PA system shouldn't be telling it much of anything.

This is an interesting point. I have been thinking of the collector/client relationship differently, but perhaps there's an inconsistency in my mental model of the problem. I would think that, ideally, the client would only need to trust that the aggregators don't collude. In particular, it wouldn't even need to trust the collector, at least not directly. Our goal would be that, as long as least one of the aggregator is honest, some standard of privacy can be enforced (batch size, DP budget, etc.). Perhaps this trust model is too pessimistic for security to be achievable? In any case, our protocol certainly doesn't achieve it right now.

**Comment by ekr** [comment]
> This is an interesting point. I have been thinking of the collector/client relationship differently, but perhaps there's an inconsistency in my mental model of the problem. I would think that, ideally, the client would only need to trust that the aggregators don't collude. In particular, it wouldn't even need to trust the collector, at least not directly. Our goal would be that, as long as least one of the aggregator is honest, some standard of privacy can be enforced (batch size, DP budget, etc.). Perhaps this trust model is too pessimistic for security to be achievable? In any case, our protocol certainly doesn't achieve it right now.

Well, I think the relationship of the client and the collector is different than the relationship with the rest of the system.

In the simplest case, the client was actually written by the collector (that's what you would see in product telemetry, for instance). So, then how does the *user* get confidence that the client is using reasonable parameters, having a set of helpers that the user can trust, etc.? At some level, they can inspect the source code, but more likely the expectation is that the vendor makes assertions about their practices and then the code is open to inspection to verify that those assertions are correct. But note that set of mechanisms needs to not just cover PA but also ensure that that software is otherwise behaving as advertised, so this is a more general problem that we need not solve here (this is where open source, reproducible builds, and binary transparency come in).

Now there is a more generic case in which the client is written separately but for some reason wants to report to the collector, in which case I would assume that the client vendor somehow imports the parameters (again, in a way we don't need to standardize) from the operator of the collector, but I would assume that here too we would expect the client vendor to assure themselves that those parameters were reasonable.

**Comment by cjpatton** [comment]
It sounds like you don't see much value in the client discovering parameters online? This might be useful, say, if the client has a binary that it can use to run many different PA tasks, with different parameters.

**Comment by ekr** [comment]
> It sounds like you don't see much value in the client discovering parameters online? This might be useful, say, if the client has a binary that it can use to run many different PA tasks, with different parameters.

Well, it's not clear to me how this case would arise. I mean, the client still has to *collect* the data before it submits it in a report, so presumably that part is code, right?

**Comment by cjpatton** [comment]
True, though it might be useful to tune the parameters used to collect the same data. I don't have a specific use case in mind, so this optimization could be premature.

**Comment by ekr** [comment]
Well but in this case, why can't the client just download it from the vendor somehow? I mean, you've probably already got some channel for updates. Why does this have to be something that this protocol solves?

**Comment by cjpatton** [comment]
Hey @ekr, have we addressed everything in this issue?
