### ISSUE TITLE
Encrypt to the leader as well

### ISSUE THREAD

**Issue by ekr** [abetterinternet/prio-documents#69]
ACME originally had this "just trust TLS" structure and then ended up with end-to-end signatures to support designs in which you might have some kind of TLS decryption device on-path (either a forward proxy on the client or a reverse proxy on the server). ISTM that similar concerns apply here, and we should just HPKE to the leader. Note that this would also simplify the protocol because you wouldn't need to have parallel structures of leader/helper and could just have:

```
PAEncryptedInputShare input_share<..2^24-1>;
```

With the convention that leader was 0.

**Comment by cjpatton** [comment]
I'd be fine with this change.

**Comment by tgeoghegan** [comment]
I think this is especially important in light of #64: if we're going to allow* batching clients to sit between real clients and leaders, then we should prevent those batching clients from being able to observe or tamper with the contents of individual reports, especially if we're going to put some information (timestamps or some unique identifier) into the report to enable aggregators to enforce query/privacy budgets.

* or rather, "if we're going to acknowledge that we can't prevent"
