### ISSUE TITLE
Derive the PA task from the parameters

### ISSUE THREAD

**Issue by cjpatton** [abetterinternet/prio-documents#72]
On the 2021/7/7 design call we decided that the ID should be derived deterministically from the serialized PAParam by, for example, hashing it. This solves a few problems simultaneously. This settles the question of whether there should be 1:1 correspondence between a task ID and the parameters used for that task.

@tgeoghegan brought up an interesting question, which is how to make the task ID unique when two different data collection tasks use the same parameters. Thoughts?

**Comment by tgeoghegan** [comment]
The consensus here is to do SHA-256 over the PDAParams structure and use that as the 32 byte PDATaskID. However, hashing a protocol message requires us to decide on a canonical representation of a protocol message, which I think forces us to decide how to encode messages on the wire. I filed #85 for that question. I'll proceed with a PR for this issue on the assumption that we'll pick JSON.

**Comment by cjpatton** [comment]
As I mentioned there, the assumption would be that we're adopting TLS' binary encoding. If so, in TLS notation, you would write `SHA-256(PDAParam)` as the hash of `PDAParam`, which itself is a serialized data structure.

**Comment by chris-wood** [comment]
> @tgeoghegan brought up an interesting question, which is how to make the task ID unique when two different data collection tasks use the same parameters. Thoughts?

All we require is that each PAParam have some unique value, right? A random nonce would probably suffice.

r.e. the encoding, yes, let's stick with TLS's wire format as @cjpatton suggests.

**Comment by tgeoghegan** [comment]
Yes, my thinking was that we would just stick 16 bytes of random data in `PDAParams` (a UUID's worth). I agree that we should stick with TLS binary encoding.
