### ISSUE TITLE
PAUploadFinishReq timestamp

### ISSUE THREAD

**Issue by chris-wood** [abetterinternet/prio-documents#75]
Currently, clients specify the report timestamp when uploading a report for a task. Presumably this timestamp is used to determine the window/batch in which a report is aggregated. Do we care if clients can spoof or change this timestamp to put reports into different batches? Since clients have no understanding of what batch their report goes into, and this is something that aggregators manage, perhaps we should drop this and let the aggregators figure out the report<>batch grouping?

**Comment by cjpatton** [comment]
> Currently, clients specify the report timestamp when uploading a report for a task. Presumably this timestamp is used to determine the window/batch in which a report is aggregated.

Yes, that's the idea.

> Do we care if clients can spoof or change this timestamp to put reports into different batches?

We have no way of ensuring that the client doesn't lie about the timestamp. This "attack" is akin to the client just lying about the input itself (see #20): It's something we can't do anything about, short of using a secure enclave on the client's machine. I think dealing with these problems is orthogonal to the spec here. On the other hand, it should our goal to allow an honest aggregator to ensure that each report appears in most one batch.

> Since clients have no understanding of what batch their report goes into, and this is something that aggregators manage, perhaps we should drop this and let the aggregators figure out the report<>batch grouping?

The timestamp and batch window is intended to allow an honest aggregator to manage this report<->batch mapping *efficiently*, i.e., with minimal state between aggregate requests. Unless we can think of a better way, I think we should keep this in.

**Comment by cjpatton** [comment]
This issue is now subsumed by #82.
