### ISSUE TITLE
Consensus protocol

### ISSUE THREAD

**Issue by chris-wood** [abetterinternet/prio-documents#8]
We currently have an open issue for tracking the consensus protocol needed for this system to work. In working through this text, we should make note of what sort of synchronization we assume between different participants of the system.

**Comment by tgeoghegan** [comment]
In the 3/17 design call we agreed that for purposes of the design doc and probably the initial deployments of Prio, we would assume that shared parameters (e.g., arithmetic circuits, primes, aggregation identifiers) would be exchanged between all parties (i.e., clients, aggregators, collector, leader) before the start of the protocol over some unspecified secure channel.

However, eventually, it should be possible for a client that wishes to use Prio to programmatically:

- discover participating servers (i.e., a directory of aggregators)
- discover the capabilities of participating servers (i.e., what algorithms do they support for secret sharing or validity proofs or aggregations? What optional protocol features do they support?)
- configure a Prio aggregation (i.e., select some number of aggregation servers, getting a unique handle, configuring field size, etc.)

**Comment by cjpatton** [comment]
One thing that's still TBD is how to choose the joint randomness. It could be as simple as having the leader choose a seed for a PRG and distributing it to the aggregators over secure channels. It could be as complicated as querying [DRAND](https://drand.love/) at some point after the shares are received by the aggregators.

**Comment by cjpatton** [comment]
To close the loop on this issue: the PDA parameters are distributed to all entities out-of-band.
