### ISSUE TITLE
Intra-batch replay detection

### ISSUE THREAD

**Issue by chris-wood** [abetterinternet/prio-documents#81]
For privacy reasons, leaders should not be allowed to replay a given report more than once within the context of a single batch. The current verify+collect model runs in a "streaming mode," wherein the leader sends slices of batch shares to helpers for verification and aggregation. 

If we changed this to require the leader to send _all_ batch shares in a single verify+collect flow, then replay prevention would be simpler: just scan the list and check for dupes. 

If we stick with the current model, then the helper must necessarily store some state (on the leader, most likely) representing the shares processed. This state could then be consulted when asked to verify+collect any new share. (We can probably spell out a number of ways to do store this state, but ideally it should not be linear in the number of shares collected so far.) We'd likely also need a way for the leader to request that the helper produce the final aggregate output once the batch is "done" being verified and collected.

**Comment by cjpatton** [comment]
> If we changed this to require the leader to send _all_ batch shares in a single verify+collect flow, then replay prevention would be simpler: just scan the list and check for dupes.

One downside to this approach is that it requires the leader to queue up the entire batch of reports before sending the first aggregate request to the helper. This may be OK for some deployments, but it might not be workable for all. 
 
> If we stick with the current model, then the helper must necessarily store some state (on the leader, most likely) representing the shares processed. This state could then be consulted when asked to verify+collect any new share. (We can probably spell out a number of ways to do store this state, but ideally it should not be linear in the number of shares collected so far.)

I think this is worth pursuing.

> We'd likely also need a way for the leader to request that the helper produce the final aggregate output once the batch is "done" being verified and collected.

This is already in the protocol. (See "output share request".)

**Comment by tgeoghegan** [comment]
> (We can probably spell out a number of ways to do store this state, but ideally it should not be linear in the number of shares collected so far.)

We could require that the leader feed the helper reports with monotonically increasing timestamps, such that the helper can simply maintain a single timestamp and reject any report older than that. However I'm not sure if that's practical given that clients may submit reports out of order.

**Comment by ekr** [comment]
One intermediate option would be to maintain a jitter buffer on the leader,
so that they keep reports for a few minutes and then feed them out in
order. You would still lose some reports, but not too many.
