### ISSUE TITLE
Choose encoding format for protocol messages

### ISSUE THREAD

**Issue by tgeoghegan** [abetterinternet/prio-documents#85]
The protocol document uses TLS notation to describe messages exchanged between servers, e.g.:
```
struct {
  uint8 config_id;
  opaque enc<1..2^16-1>;
  opaque payload<1..2^16-1>;
} PDAEncryptedInputShare;
```

However it's not clear how we will actually encode messages on the wire. JSON bodies seems most conventional for REST APIs, but at least @ekr assumed we would use TLS encoding. We should choose an encoding format and update the document appropriately.

**Comment by cjpatton** [comment]
The document should specify the encoding. We went with TLS binary encoding because it's what most folks were comfortable with at the time of writing. FWIW, I'm happy to change course if there's a good reason to :)

**Comment by chris-wood** [comment]
I think we should close this and stick with TLS.

**Comment by tgeoghegan** [comment]
Having thought about it over dinner: I raised this because I assumed that "most people" would prefer JSON bodies over a binary encoding, but personally I've never liked JSON (too much `"`) so I'll let "most people" argue for it somewhere down the line instead of making a poor case for it myself.
